### PR TITLE
Fix lang single stmt bug & add more cli languages

### LINKED ISSUE #50: Error message on single statements without specifying lang
Currently the cli throws following error when calling it with a single statement and without specifying a language via the `--lang` flag:

```
Please use lang 'auto' only in combination of valid file paths as file input
```

As a single file does not have comment identifiers, there should no language be needed to call CCom.

### PR DESCRIPTION
**Pull request by marcauberer**
- Fix #50 
- Add more languages to the cli
- Update README accordingly
- Sort languages in README alphabetically

### CODE REVIEW

File: cli/preprocessor.go [hunk 1]
```diff
@@ -96,15 +96,15 @@ func analyze(
...
-
 	// Get raw data strings
 	if !modeSingle {
+		// Ensure value of comment char
+		if *lineCommentIden == "" && *blockCommentIdenOpen == "" && *blockCommentIdenClose == "" {
+			*lineCommentIden, *blockCommentIdenOpen, *blockCommentIdenClose = getCommentIdenFromLang(lang, *fileInput)
+		} else if (*blockCommentIdenOpen == "" && *blockCommentIdenClose != "") || (*blockCommentIdenOpen != "" && *blockCommentIdenClose == "") {
+			util.Error("You cannot specify only one of blockCommentIdenOpen and blockCommentIdenClose. Please specify both or none.", true)
+		}
+
```
Comment (Splines) [inline cli/preprocessor.go:107]: I'm wondering how this fixes #50 since you wrapped the if statement around another error and not 

```
Please use lang 'auto' only in combination of valid file paths as file input
```

**Review by Splines — COMMENTED** [review]
Nice that you've added more languages to the Readme 👌

File: cli/preprocessor.go (hunk 1 above)
Comment (marcauberer) [reply cli/preprocessor.go:107]: @Splines the if statement is also wrapped around the method call to `getCommentIdenFromLang()` where this error message is thrown, so when the method isn't even called, no error can be thrown ;)

Comment (Splines) [reply cli/preprocessor.go:107]: ah, I see 👌

**Review by Splines — APPROVED** [review]
